### ISSUE TITLE
Can't update RemoteConfig to the latest version

### ISSUE THREAD

**Issue by AGulev** [defold/extension-firebase-remoteconfig#12]
If RemoteConfig update to the latest version `10.19.0` then the extension can't be built.

Here is logs 

```
/var/folders/sk/1rps9wzs79zdj9f2wz8m0yf00000gn/T/job14189348262439117672/CocoaPodsService/Pods/FirebaseRemoteConfig/FirebaseRemoteConfig/Swift/PropertyWrapper/RemoteConfigProperty.swift:18:21: error: no such module 'FirebaseRemoteConfigInternal'
  @_exported import FirebaseRemoteConfigInternal
                    ^
error: fatalError

com.defold.extender.ExtenderException: java.io.IOException: error: emit-module command failed with exit code 1 (use -v to see invocation)
/var/folders/sk/1rps9wzs79zdj9f2wz8m0yf00000gn/T/job14189348262439117672/CocoaPodsService/Pods/FirebaseRemoteConfig/FirebaseRemoteConfig/Swift/PropertyWrapper/RemoteConfigProperty.swift:18:21: error: no such module 'FirebaseRemoteConfigInternal'
  @_exported import FirebaseRemoteConfigInternal
                    ^
error: fatalError

	at com.defold.extender.Extender.buildEngine(Extender.java:2162)
	at com.defold.extender.Extender.build(Extender.java:2494)
	at com.defold.extender.AsyncBuilder.asyncBuildEngine(AsyncBuilder.java:115)
	at com.defold.extender.AsyncBuilder$$FastClassBySpringCGLIB$$3a887347.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: error: emit-module command failed with exit code 1 (use -v to see invocation)
/var/folders/sk/1rps9wzs79zdj9f2wz8m0yf00000gn/T/job14189348262439117672/CocoaPodsService/Pods/FirebaseRemoteConfig/FirebaseRemoteConfig/Swift/PropertyWrapper/RemoteConfigProperty.swift:18:21: error: no such module 'FirebaseRemoteConfigInternal'
  @_exported import FirebaseRemoteConfigInternal
                    ^
error: fatalError

	at com.defold.extender.ProcessExecutor.execute(ProcessExecutor.java:77)
	at com.defold.extender.ProcessExecutor$1.call(ProcessExecutor.java:120)
	at com.defold.extender.ProcessExecutor$1.call(ProcessExecutor.java:117)
	... 4 more
```

[log.txt.zip](https://github.com/defold/extension-firebase-remoteconfig/files/13973919/log.txt.zip)

https://github.com/defold/extension-firebase-remoteconfig/blob/bb3188b7c040da9ed5a1552c49db6f65cee57ec6/firebase_remoteconfig/manifests/ios/Podfile#L2

It seems like there was a change in RemoteConfig in `10.2.0`:
https://github.com/search?q=repo%3Afirebase%2Ffirebase-ios-sdk%20FirebaseRemoteConfigInternal&type=code

**Comment by AGulev** [comment]
@britzl 
Here is a Swift related issue I was talking about. I'm not entirely sure what's going on there. Maybe you'll find out.

**Comment by AGulev** [comment]
[log.txt](https://github.com/defold/extension-firebase-remoteconfig/files/14550792/log.txt)

**Comment by AGulev** [comment]
@ekharkunov I still see the issue https://github.com/defold/extension-firebase-remoteconfig/actions/runs/17204248027/job/48801237413

**Comment by AGulev** [comment]
hmm, let me fix that (I get used that we use stage server everywhere)

**Comment by AGulev** [comment]
Fixed in Defold 1.11.0

@ekharkunov Thank you!
